apiVersion: v1
kind: Deployment
metadata:
  name: redis-app-deploy
  labels:
    name: redis-app-deploy
    app: demo-redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: demo-voting-app

  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-app-pod
        app: demo-redis-app
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          